# Generated by Django 4.1 on 2023-10-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desciption', models.TextField()),
                ('inspiration', models.CharField(max_length=200)),
                ('coordinate_1', models.FloatField(default=0)),
                ('coordinate_2', models.FloatField(default=0)),
            ],
        ),
    ]
