# Generated by Django 4.1 on 2023-10-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='coordinate_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='coordinate_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark')),
            ],
        ),
    ]
